import {Animal} from "$domain/entities/Animals";
import {DateHelper} from "$utils/dateUtils.utils";

export const UnitAnimal = {
    puppy: new Animal({
        id: "67164a84291bcc737b9a7e4a",
        ownerId: "67164a84291bcc737b9a7e3a",
        name: "Puppy",
        type: "Dog",
        race: "Labrador",
        age: 1,
        picture: "",
        description:"",
        likes: [],
        createdAt: DateHelper.daysAgo(15),
        updatedAt: new Date(),
    }),
    carpette: new Animal({
        id: "67164a84291bcc737b9a7e4b",
        ownerId: "67164a84291bcc737b9a7e3a",
        name: "Carpette",
        type: "Fish",
        race: "Koi",
        age: 1,
        picture: "",
        description:"",
        likes: [],
        createdAt: DateHelper.daysAgo(13),
        updatedAt: new Date(),
    }),
    noona: new Animal({
        id: "67164a84291bcc737b9a7e4c",
        ownerId: "67164a84291bcc737b9a7e3a",
        name: "Noona",
        type: "Cat",
        race: "Européen",
        age: 1,
        picture: "",
        description:"",
        likes: [],
        createdAt: DateHelper.daysAgo(10),
        updatedAt: new Date(),
    }),
    hubert: new Animal({
        id: "67164a84291bcc737b9a7e4d",
        ownerId: "67164a84291bcc737b9a7e3a",
        name: "Hubert",
        type: "Hamster",
        race: "",
        age: 1,
        picture: "",
        description:"",
        likes: [],
        createdAt: DateHelper.daysAgo(7),
        updatedAt: new Date(),
    }),
    ham: new Animal({
        id: "67164a84291bcc737b9a7e4e",
        ownerId: "67164a84291bcc737b9a7e3a",
        name: "Ham",
        type: "Pig",
        race: "",
        age: 1,
        picture: "",
        description:"",
        likes: ["like-1", "like-2"],
        createdAt: DateHelper.daysAgo(1),
        updatedAt: new Date(),
    }),
}