import {Post} from "$domain/entities/Posts";
import {DateHelper} from "$utils/dateUtils.utils";

export const UnitPost = {
    post1: new Post({
        id: "post-1",
        authorId: "67164a84291bcc737b9a7e3a",
        textContent: "Premier post",
        photoContent: [],
        likes: [],
        comments: ["Super post !", "Je suis d'accord"],
        updated: false,
        createdAt: DateHelper.daysAgo(15),
        updatedAt: new Date(),
    }),
    post2: new Post({
        id: "post-2",
        authorId: "67164a84291bcc737b9a7e3a",
        textContent: "Deuxième post",
        photoContent: [],
        likes: [],
        comments: [],
        updated: false,
        createdAt: DateHelper.daysAgo(13),
        updatedAt: new Date(),
    }),
    post3: new Post({
        id: "post-3",
        authorId: "67164a84291bcc737b9a7e3a",
        textContent: "Troisième post",
        photoContent: [],
        likes: [],
        comments: [],
        updated: false,
        createdAt: DateHelper.daysAgo(10),
        updatedAt: new Date(),
    }),
    post4: new Post({
        id: "post-4",
        authorId: "67164a84291bcc737b9a7e3a",
        textContent: "Quatrième post",
        photoContent: [],
        likes: [],
        comments: [],
        updated: false,
        createdAt: DateHelper.daysAgo(5),
        updatedAt: new Date(),
    }),
    post5: new Post({
        id: "post-5",
        authorId: "67164a84291bcc737b9a7e3a",
        textContent: "Cinquième post",
        photoContent: [],
        likes: ["like-1", "like-2"],
        comments: ["comment-1", "comment-2"],
        updated: false,
        createdAt: DateHelper.daysAgo(1),
        updatedAt: new Date(),
    }),
}