import {User} from "$domain/entities/Users"
import {DateHelper} from "$utils/dateUtils.utils";

export const UnitUser = {
    john: new User({
        id: "550e8400-e29b-41d4-a716-446655440000",
        name: "Doe",
        firstName: "John",
        email: "john.doe@johndoe.com",
        password: "$argon2id$v=19$m=1024,t=4,p=2$Zsd3m9/6awmtUbyNBP92jQ$nvJo/KhXqQvV7SZLgCSc+UmPSU3rSqjmSxrL8fZ7HnA",
        role: "USER",
        createdAt: DateHelper.daysAgo(30),
        updatedAt: DateHelper.hoursAgo(2),
        profileDescription: "",
        profilePicture: "",
        refreshToken: "",
    }),
    jane: new User({
        id: "550e8400-e29b-41d4-a716-446655440001",
        name: "Doe",
        firstName: "Jane",
        email: "jane.doe@janedoe.com",
        password: "$argon2id$v=19$m=1024,t=4,p=2$Zsd3m9/6awmtUbyNBP92jQ$nvJo/KhXqQvV7SZLgCSc+UmPSU3rSqjmSxrL8fZ7HnA",
        role: "USER",
        createdAt: DateHelper.daysAgo(15),
        updatedAt: DateHelper.minutesAgo(30),
        profileDescription: "",
        profilePicture: "",
        refreshToken: "",
    }),
    loly: new User({
        id: "550e8400-e29b-41d4-a716-446655440002",
        name: "Doe",
        firstName: "Loly",
        email: "loly.doe@lolydoe.com",
        password: "$argon2id$v=19$m=1024,t=4,p=2$Zsd3m9/6awmtUbyNBP92jQ$nvJo/KhXqQvV7SZLgCSc+UmPSU3rSqjmSxrL8fZ7HnA",
        role: "ADMIN",
        createdAt: DateHelper.daysAgo(15),
        updatedAt: DateHelper.minutesAgo(30),
        profileDescription: "",
        profilePicture: "",
        refreshToken: "",
    }),
    modette: new User({
        id: "550e8400-e29b-41d4-a716-446655440003",
        name: "Doe",
        firstName: "Modette",
        email: "modette.doe@modettedoe.com",
        password: "$argon2id$v=19$m=1024,t=4,p=2$Zsd3m9/6awmtUbyNBP92jQ$nvJo/KhXqQvV7SZLgCSc+UmPSU3rSqjmSxrL8fZ7HnA",
        role: "MODERATOR",
        createdAt: DateHelper.daysAgo(15),
        updatedAt: DateHelper.minutesAgo(30),
        profileDescription: "",
        profilePicture: "",
        refreshToken: "",
    })
}